import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import GenreList from "@/components/GenerList";
import { Analytics } from "@vercel/analytics/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Movie Detailer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center p-4 border-b shadow-sm">
          <Link href="/">
            <Image
              src="/logo.jpg"
              alt="Logo"
              width={120}
              height={40}
              className="h-auto w-auto"
              priority
            />
          </Link>
        </header>
        <Header />
        <GenreList />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
